spring:
  cloud:
   kubernetes:
     discovery:
       enabled: false
   stream:
     kafka:
       binder:
         brokers: localhost:9092
     bindings:
       command-out:
         destination: orders
         contentType: application/json
       query-in:
         destination: orders
         contentType: application/json
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop   #tambien se puede poner a update.